#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: org.example.api.mybatis.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # mybatis在控制台输出日志
    map-underscore-to-camel-case: true # 驼峰命名
# 应用服务 WEB 访问端口
server:
  port: 9019 # 启动端口
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    url: jdbc:mysql://ip:3306/kcglsql # 数据库url
    username:  # 数据库用户名
    password:  # 数据库密码
jwt:
  expiration:  # token 过期时间
  key:  # token 加密解密密钥